### ISSUE TITLE
$fh.cloud (and $fh.act?) Parsing of Error Responses

### ISSUE THREAD

**Issue by evanshortiss** [feedhenry/fh-js-sdk#109]
I'd like to know if it would be ok to change the way _handleError_ works when called in the event of an AJAX error.

Currently my express application returns a specific response format for _all_ requests, even when I return a 500 error for example. When I return this 500 the SDK smarts kick in and parse it. As I don't conform to the format it expects, the _errraw_ returned to the failure callback is **undefined**, but I need the _errraw_ to present a useful error message to users.

I'd like to propose changing [this line](https://github.com/feedhenry/fh-js-sdk/blob/master/src/modules/handleError.js#L10) to something like:

```javascript 
errraw = res.error || res.msg || res;
```

This would mean that if a request doesn't have an _error_ or _msg_ result, such as in my case, it will still be returned to the error callback as a user would expect. I believe this would retain compatibility with previous applications too so it's safe.

**Comment by jasonmadigan** [comment]
@evanshortiss yeah, I'd be in favour of a patch like this. It's a bit too "magical" right now.

**Comment by wei-lee** [comment]
:clap:

**Comment by evanshortiss** [comment]
PR done ;)

**Comment by evanshortiss** [comment]
Guess this can be closed since it was merged.
