### ISSUE TITLE
$fh.sec - Cannot supply a custom Secret

### ISSUE THREAD

**Issue by evanshortiss** [feedhenry/fh-js-sdk#125]
Currently $fh.sec's keygen operation generates a random secret for the key. If I added a backwards compatible patch to allow for a custom secret would it be of use? We need it in an application we're working on.

**Comment by wei-lee** [comment]
@evanshortiss  as long as it's backward compatible, I see no problem with that.

**Comment by camilamacedo86** [comment]
@evanshortiss shows that you raise a question here and @wei-lee already answered it more than 2 years ago. In this way, we are closing this one. Please, feel free to contact us.
